import math
import os

import random

#from ..feeder.feeder_ntu import Feeder

import torch
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter

import numpy as np

from collections import OrderedDict, defaultdict
# from feeder.feeder_ntu import Feeder
from copy import deepcopy
from tqdm import tqdm, trange

from .TransformerEncoder import EncoderLayer, EncoderLayerST
from .SkeleEmbed import *
from .operations import *

writer = SummaryWriter()

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

# Coords to Coords
class PairedCoordsTransformer(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(PairedCoordsTransformer, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key=len)), t_m)
        self.window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.window_enc, std=.02)
        self.segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key=len)) * (t_m) * 3))

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool=False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio < 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_ * B, F, J, C)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key=len)), C, device=src.device)

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]

        N, S, F, J, C = x_src.shape
        W = F//self.t_m

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        ground_truth = x_src.clone()

        ground_truth = ground_truth.view(N, S, W, self.t_m, J, C)

        ground_truth = ground_truth.view(N, S*W, self.t_m, J, C)

        x = self.cnn_projector(x_src)

        x = x.view(N, S * W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:
            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction = prediction.view(N, -1, self.t_m, J, C)

            return compute_loss(prediction, ground_truth, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x

# Coords to Spline
class SegmentedSplineCoordTransformerVel2(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(SegmentedSplineCoordTransformerVel2, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)
        self.window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.window_enc, std=.02)
        self.segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio< 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)
        if self.train:
            src_motion = compute_splines(src.clone(), self.t_m)
            src_vel = compute_splines(compute_displacement(src.clone()), self.t_m)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        if self.train:
            x_motion = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_vel = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_motion[:] = 1e-9

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]
                if self.train:
                    x_motion[:, i, :, j] = src_motion[:, :, joint]
                    x_vel[:, i, :, j] = src_vel[:, :, joint]

        if self.train:
            N, S, W, J, C, coeffs = x_motion.shape

            ground_truth_spline = x_motion.clone()

            ground_truth_spline = ground_truth_spline.view(N, -1, J, C, coeffs)

            ground_truth_vel = x_vel.view(N, -1, J, C, coeffs)
        else:
            W = F//self.t_m

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        x = self.cnn_projector(x_src)

        x = x.view(N, S*W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction_spline, prediction_vel = prediction[:, :, :J*coeffs*C], prediction[:, :, J*coeffs*C:]

            # [N, 4, frame_mask_ratio*W, J, 3] -> [N, frame_mask_ratio*W, J, 3, 4]
            prediction_spline = prediction_spline.view(N, -1, J, C, coeffs)

            prediction_vel = prediction_vel.view(N, -1, J, C, coeffs)

            return compute_loss(prediction_spline, ground_truth_spline, True, idx_predict, self.loss_fn) + compute_loss(prediction_vel, ground_truth_vel, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x

# SPLINE TO SPLINE
class PairedSplineTransformerVel2(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(PairedSplineTransformerVel2, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3*4*(t_m-3)*2, d_model, len(max(segments, key = len)), 1)
        self.window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.window_enc, std=.02)
        self.segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio< 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)

        src_motion = compute_splines(src.clone(), self.t_m)
        src_vel = compute_splines(compute_displacement(src.clone()), self.t_m)

        N, F, J, C = src.shape

        x_motion = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
        x_vel = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
        x_motion[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                x_motion[:, i, :, j] = src_motion[:, :, joint]
                x_vel[:, i, :, j] = src_vel[:, :, joint]

        if self.train:
            N, S, W, J, C, coeffs = x_motion.shape

            ground_truth_spline = x_motion.clone()

            ground_truth_spline = ground_truth_spline.view(N, -1, J, C, coeffs)

            ground_truth_vel = x_vel.view(N, -1, J, C, coeffs)
        else:
            N, S, W, J, C, coeffs = x_motion.shape

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        x_src = torch.cat([x_motion, x_vel], dim = -1)

        x_src = x_src.view(N, S, W, J, -1)

        x = self.cnn_projector(x_src)

        x = x.view(N, S*W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction_spline, prediction_vel = prediction[:, :, :J*coeffs*C], prediction[:, :, J*coeffs*C:]

            # [N, 4, frame_mask_ratio*W, J, 3] -> [N, frame_mask_ratio*W, J, 3, 4]
            prediction_spline = prediction_spline.view(N, -1, J, C, coeffs)

            prediction_vel = prediction_vel.view(N, -1, J, C, coeffs)

            return compute_loss(prediction_spline, ground_truth_spline, True, idx_predict, self.loss_fn) + compute_loss(prediction_vel, ground_truth_vel, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x

class PairedSplineCoordsTransformerVel2(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(PairedSplineCoordsTransformerVel2, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3*4*(t_m-3)*2, d_model, len(max(segments, key = len)), 1)
        self.window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.window_enc, std=.02)
        self.segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key=len)) * (t_m) * 3))

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio< 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)
        src_motion = compute_splines(src.clone(), self.t_m)
        src_vel = compute_splines(compute_displacement(src.clone()), self.t_m)

        N, F, J, C = src.shape

        ground_truth = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device = src.device)

        x_motion = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
        x_vel = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
        x_motion[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                ground_truth[:, i, :, j] = src[:, :, joint]
                x_motion[:, i, :, j] = src_motion[:, :, joint]
                x_vel[:, i, :, j] = src_vel[:, :, joint]

        N, S, W, J, C, coeffs = x_motion.shape

        ground_truth = ground_truth.view(N, S, W, self.t_m, J, C)

        ground_truth = ground_truth.view(N, S*W, self.t_m, J, C)

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        x_src = torch.cat([x_motion, x_vel], dim = -1)

        x_src = x_src.view(N, S, W, J, -1)

        x = self.cnn_projector(x_src)

        x = x.view(N, S*W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction = prediction.view(N, -1, self.t_m, J, C)

            return compute_loss(prediction, ground_truth, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x


class CoordTransformerBaseNoPE(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(CoordTransformerBaseNoPE, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        self.enc_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):
            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]

        S = len(segments)
        W = F//self.t_m

        x = self.cnn_projector(x_src)

        x = x.view(N, S*W, -1)

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        x = x.view(N, S, W, self.d_model)

        if not avg_pool:
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=1)
        else:
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=[1, 2, 3])

        return x



class CoordTransformerBase(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(CoordTransformerBase, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)
        self.window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.window_enc, std=.02)
        self.segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        self.enc_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):
            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]

        S = len(segments)
        W = F//self.t_m

        x = self.cnn_projector(x_src)

        x = x.view(N, S*W, -1)

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        x = x.view(N, S, W, self.d_model)

        if not avg_pool:
            x += self.window_enc[:, :, :W] + self.segment_enc[:, :S]
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=1)
        else:
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=[1, 2, 3])

        return x


class CoordTransformerBaseDecPE(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(CoordTransformerBaseDecPE, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)
        self.dec_window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.dec_window_enc, std=.02)
        self.dec_segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.dec_segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        self.enc_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):
            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]

        S = len(segments)
        W = F//self.t_m

        x = self.cnn_projector(x_src)

        x = x.view(N, S*W, -1)

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        x = x.view(N, S, W, self.d_model)

        if not avg_pool:
            x += self.dec_window_enc[:, :, :W] + self.dec_segment_enc[:, :S]
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=1)
        else:
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=[1, 2, 3])

        return x


class CoordTransformerBaseEncPE(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(CoordTransformerBaseEncPE, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)
        self.enc_window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.enc_window_enc, std=.02)
        self.enc_segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.enc_segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        self.enc_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):
            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]

        S = len(segments)
        W = F//self.t_m

        x = self.cnn_projector(x_src)

        x = x.view(N, S, W, -1)

        x += self.enc_window_enc[:, :, :W] + self.enc_segment_enc[:, :S]

        x = x.view(N, S*W, -1)

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        x = x.view(N, S, W, self.d_model)

        if not avg_pool:
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=1)
        else:
            x = x.view(N_, B, S, W, self.d_model)
            if self.body_avg:
                x = torch.mean(x, dim=[1, 2, 3])

        return x


# Coords to Spline Encoder PE +
class SegmentedSplineCoordTransformerVel2EncPE(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(SegmentedSplineCoordTransformerVel2EncPE, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)

        self.enc_window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.enc_window_enc, std=.02)
        self.enc_segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.enc_segment_enc, std=.02)

        self.dec_window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.dec_window_enc, std=.02)
        self.dec_segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.dec_segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio< 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)
        if self.train:
            src_motion = compute_splines(src.clone(), self.t_m)
            src_vel = compute_splines(compute_displacement(src.clone()), self.t_m)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        if self.train:
            x_motion = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_vel = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_motion[:] = 1e-9

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]
                if self.train:
                    x_motion[:, i, :, j] = src_motion[:, :, joint]
                    x_vel[:, i, :, j] = src_vel[:, :, joint]

        if self.train:
            N, S, W, J, C, coeffs = x_motion.shape

            ground_truth_spline = x_motion.clone()

            ground_truth_spline = ground_truth_spline.view(N, -1, J, C, coeffs)

            ground_truth_vel = x_vel.view(N, -1, J, C, coeffs)
        else:
            W = F//self.t_m

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        x = self.cnn_projector(x_src)

        x = x.view(N, S, W, -1)

        x += self.enc_segment_enc[:, :S] + self.enc_window_enc[:, :, :W]

        x = x.view(N, S*W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x += self.dec_window_enc[:, :, :W] + self.dec_segment_enc[:, :S]

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction_spline, prediction_vel = prediction[:, :, :J*coeffs*C], prediction[:, :, J*coeffs*C:]

            # [N, 4, frame_mask_ratio*W, J, 3] -> [N, frame_mask_ratio*W, J, 3, 4]
            prediction_spline = prediction_spline.view(N, -1, J, C, coeffs)

            prediction_vel = prediction_vel.view(N, -1, J, C, coeffs)

            return compute_loss(prediction_spline, ground_truth_spline, True, idx_predict, self.loss_fn) + compute_loss(prediction_vel, ground_truth_vel, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                # x += self.dec_window_enc[:, :, :W] + self.dec_segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x

class SegmentedSplineCoordTransformerVel2EncPEOnly(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(SegmentedSplineCoordTransformerVel2EncPEOnly, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)

        self.enc_window_enc = nn.Parameter(torch.rand(1, 1, max_seq_length, d_model))
        trunc_normal_(self.enc_window_enc, std=.02)
        self.enc_segment_enc = nn.Parameter(torch.rand(1, len(segments), 1, d_model))
        trunc_normal_(self.enc_segment_enc, std=.02)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio< 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)
        if self.train:
            src_motion = compute_splines(src.clone(), self.t_m)
            src_vel = compute_splines(compute_displacement(src.clone()), self.t_m)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        if self.train:
            x_motion = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_vel = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_motion[:] = 1e-9

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]
                if self.train:
                    x_motion[:, i, :, j] = src_motion[:, :, joint]
                    x_vel[:, i, :, j] = src_vel[:, :, joint]

        if self.train:
            N, S, W, J, C, coeffs = x_motion.shape

            ground_truth_spline = x_motion.clone()

            ground_truth_spline = ground_truth_spline.view(N, -1, J, C, coeffs)

            ground_truth_vel = x_vel.view(N, -1, J, C, coeffs)
        else:
            W = F//self.t_m

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        x = self.cnn_projector(x_src)

        x = x.view(N, S, W, -1)

        x += self.enc_segment_enc[:, :S] + self.enc_window_enc[:, :, :W]

        x = x.view(N, S*W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction_spline, prediction_vel = prediction[:, :, :J*coeffs*C], prediction[:, :, J*coeffs*C:]

            # [N, 4, frame_mask_ratio*W, J, 3] -> [N, frame_mask_ratio*W, J, 3, 4]
            prediction_spline = prediction_spline.view(N, -1, J, C, coeffs)

            prediction_vel = prediction_vel.view(N, -1, J, C, coeffs)

            return compute_loss(prediction_spline, ground_truth_spline, True, idx_predict, self.loss_fn) + compute_loss(prediction_vel, ground_truth_vel, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                # x += self.dec_window_enc[:, :, :W] + self.dec_segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x


class SegmentedSplineCoordTransformerVel2NoPE(nn.Module):
    def __init__(self, segments, d_model, num_heads, num_layers_enc, num_layers_dec, d_ff, max_seq_length, dropout, t_m = 5, mask_mode = "random", loss_weight = 1, body_avg = True):
        super(SegmentedSplineCoordTransformerVel2NoPE, self).__init__()
        self.t_m = t_m

        self.cnn_projector = SpatialEmbedderJustCNN(3, d_model, len(max(segments, key = len)), t_m)

        self.enc_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_enc))])
        self.dec_layers = nn.ModuleList(
            [EncoderLayer(d_model, num_heads, d_ff, dropout) for _ in range(int(num_layers_dec))])

        self.mask_token_frame = nn.Parameter(torch.zeros(1, 1, d_model))
        trunc_normal_(self.mask_token_frame, std=.02)

        self.linear_predictor = nn.Linear(d_model, (len(max(segments, key = len))  * (t_m - 3) * 4 * 3)*2)

        # self.linear_predictor_spatial = nn.Linear(d_model, out_channels)

        self.enc_norm = nn.LayerNorm(d_model)
        self.dec_norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model
        self.num_heads = num_heads

        self.loss_fn = nn.MSELoss()

        self.mask_mode = mask_mode

        self.body_avg = body_avg

        self.loss_weight_spline = loss_weight
        self.loss_weight_displacement = loss_weight

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            ### From MAMP & MAE
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, src, segments, frame_mask_ratio, avg_pool = False):
        """
        :param src: [N, C, F, J, B]
        :param segments: tuple of joints in segments
        :param frame_mask_ratio: float
        :return: list of loss (pre-train) or latent representation of losses ([N, len(segments), W, d_model])
        """

        assert frame_mask_ratio >= 0. and frame_mask_ratio< 1, "Must be between 0.0 to 1.0 including 0 for no masking"

        N_, C, F, J, B = src.shape

        # [N, C, F, J, B] -> [N, B, F, J, C]
        src = (src.permute(0, 4, 2, 3, 1).contiguous()).view(N_*B, F, J, C)
        if self.train:
            src_motion = compute_splines(src.clone(), self.t_m)
            src_vel = compute_splines(compute_displacement(src.clone()), self.t_m)

        N, F, J, C = src.shape

        x_src = torch.zeros(N, len(segments), F, len(max(segments, key = len)), C, device=src.device)

        if self.train:
            x_motion = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_vel = torch.zeros(N, len(segments), src_motion.shape[1], len(max(segments, key = len)), C, src_motion.shape[-1], device=src.device)
            x_motion[:] = 1e-9

        x_src[:] = 1e-9

        for i, segment in enumerate(segments):

            for j, joint in enumerate(segment):
                x_src[:, i, :, j] = src[:, :, joint]
                if self.train:
                    x_motion[:, i, :, j] = src_motion[:, :, joint]
                    x_vel[:, i, :, j] = src_vel[:, :, joint]

        if self.train:
            N, S, W, J, C, coeffs = x_motion.shape

            ground_truth_spline = x_motion.clone()

            ground_truth_spline = ground_truth_spline.view(N, -1, J, C, coeffs)

            ground_truth_vel = x_vel.view(N, -1, J, C, coeffs)
        else:
            W = F//self.t_m

        if self.mask_mode.lower() == "kinetic":
            x_orig = x_src.clone()
            x_orig = x_orig.view(N, S, W, self.t_m, J, C)

        x = self.cnn_projector(x_src)

        x = x.view(N, S, W, -1)

        x = x.view(N, S*W, -1)

        if self.training:
            if self.mask_mode.lower() == "random":
                x, idx_predict, unmasked, restore = generate_mask_frames(x, frame_mask_ratio)
            elif self.mask_mode.lower() == "kinetic":
                x, idx_predict, unmasked, restore = kinetic_mask_frames(x, x_orig, frame_mask_ratio)
            else:
                pass

        enc_output = x

        for enc_layer in self.enc_layers:

            enc_output = enc_layer(enc_output)

        x = self.enc_norm(enc_output)

        if self.training:

            # [N, (1 - frame_mask_ratio) * W, d_model] -> [N, W, d_model]
            x = add_mask_tokens(x, restore, self.mask_token_frame)

            x = x.view(N, S, W, -1)

            x = x.view(N, W * S, -1)

            # [N, W, d_model] -> [N, W, d_model]
            for dec_layer in self.dec_layers:
                x = dec_layer(x)
            dec_output = self.dec_norm(x)

            # [N, W, d_model] -> [N, frame_mask_ratio*W, d_model]
            masked_emb = torch.gather(dec_output, dim=1, index=idx_predict.unsqueeze(-1).repeat(1, 1, self.d_model))

            # [N, d_model, frame_mask_ratio*W, 1, 1] -> [N, 4, frame_mask_ratio*W, J, 3]
            prediction = self.linear_predictor(masked_emb)

            prediction_spline, prediction_vel = prediction[:, :, :J*coeffs*C], prediction[:, :, J*coeffs*C:]

            # [N, 4, frame_mask_ratio*W, J, 3] -> [N, frame_mask_ratio*W, J, 3, 4]
            prediction_spline = prediction_spline.view(N, -1, J, C, coeffs)

            prediction_vel = prediction_vel.view(N, -1, J, C, coeffs)

            return compute_loss(prediction_spline, ground_truth_spline, True, idx_predict, self.loss_fn) + compute_loss(prediction_vel, ground_truth_vel, True, idx_predict, self.loss_fn)

        else:
            x = x.view(N, S, W, self.d_model)

            if not avg_pool:
                # x += self.dec_window_enc[:, :, :W] + self.dec_segment_enc[:, :S]
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=1)

            else:
                x = x.view(N_, B, S, W, self.d_model)
                if self.body_avg:
                    x = torch.mean(x, dim=[1, 2, 3])

            return x
