# data
feeder: feeder.feeder_ntu.Feeder
pretrain_feeder_args:
  data_path: data/pku_v2/PKUv2_XSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  occlude: False #True

lep_train_feeder_args:
  data_path: data/pku_v2/PKUv2_XSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  occlude: False #True

lep_val_feeder_args:
  data_path: data/pku_v2/PKUv2_XSub.npz
  split: test
  debug: False
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False
  occlude: False #True

base_transformer: model.transformers.CoordTransformerBaseDecPE

# model
model: model.transformers.SegmentedSplineCoordTransformerVel2EncPE
model_args:
  # Head, Chest, Spine, L Bicep, L Forearm, L Fingers, L Thumb, L Palm, R Bicep, R Forearm, R Fingers, R Thumb, R Palm, Pelvis, L Thigh, L Knee Foot, R Thigh and R Knee Foot
  # 52.3%
  segments: [[2, 3], [2, 20], [4, 20], [4, 5], [5, 6], [6, 7], [7, 21], [7, 22], [8, 20], [8, 9], [9, 10], [10, 11], [11, 23], [11, 24], [1, 20], [0, 1], [0, 12], [12, 13], [13, 14], [14, 15], [0, 16], [16, 17], [17, 18], [18, 19]]
  ##### Testing Zone
  # 52.2% segments: [[2, 3, 20], [4, 8, 20], [0, 1, 20], [4, 5, 20], [5, 6, 7], [6, 7, 21], [6, 7, 22], [7, 21, 22], [8, 9, 20], [9, 10, 11], [10, 11, 23], [10, 11, 24], [11, 23, 24], [0, 12, 16], [0, 12, 13], [13, 14, 15], [0, 16, 17], [17, 18, 19]] # 52.4%
  # 51% segments: [[2, 3, 4, 8, 20], [1, 4, 8, 20], [4, 5, 20], [5, 6, 7], [21], [22], [8, 9, 20], [9, 10, 11], [3], [4], [0, 1, 12, 16], [0, 12, 13, 14, 15], [0, 16, 17, 18, 19]]
  # 48% segments: [[2, 3, 20], [1, 4, 8, 20], [4, 5, 6], [6, 7], [21], [22], [8, 9, 10], [10, 11], [23], [24], [0, 1, 12, 16], [12, 13, 14, 15], [16, 17, 18, 19]]
  # Head, Chest, L Bicep, L Forearm, L Hand, R Bicep, R Forearm, R Hand, Pelvis, L Leg, R Leg
  # 53.6% + 51.9 + 53 + 52.1 + 52.7
  #segments: [[2, 3, 4, 8], [1, 4, 8, 20], [1, 4, 5, 20], [4, 5, 6, 7], [6, 7, 21, 22], [1, 8, 9, 20], [8, 9, 10, 11], [10, 11, 23, 24], [0, 1, 12, 16], [12, 13, 14, 15], [16, 17, 18, 19]]
  # 52.1% segments: [[2, 3, 4, 8, 20], [1, 4, 8, 20], [4, 5, 20], [5, 6, 7], [6, 7, 21], [6, 7, 22], [8, 9, 20], [9, 10, 11], [10, 11, 23], [10, 11, 24], [0, 1, 12, 16], [0, 12, 13, 14, 15], [0, 16, 17, 18, 19]]
  # 52% segments: [[2, 3, 4, 8, 20], [1, 4, 8, 20], [4, 5, 20], [5, 6, 7], [6, 7, 21], [6, 7, 22], [8, 9, 20], [9, 10, 11], [10, 11, 23], [10, 11, 24], [0, 1, 12, 16], [0, 12, 13, 14, 15], [0, 16, 17, 18, 19]]
  # 48.1% segments: [[2, 3, 4, 8, 20], [1, 4, 8, 12, 16],[5, 6, 7, 21, 22], [9, 10, 11, 23, 24], [4, 5, 20], [5, 6, 7], [8, 9, 20], [9, 10, 11], [0, 1, 12, 16], [0, 12, 13, 14, 15], [0, 16, 17, 18, 19]]
  # 49.8% segments: [[1, 2, 3, 4, 8, 20], [0, 1, 4, 8, 12, 16],[4, 5, 6, 7, 21, 22], [8, 9, 10, 11, 23, 24], [0, 1, 12, 13, 14, 15], [0, 1, 16, 17, 18, 19]]
  # 50.0 segments: [[1, 2, 3, 4, 8, 20], [0, 1, 4, 8, 12, 16], [4, 5, 6, 7, 20], [6, 7, 21, 22], [8, 9, 10, 11, 20], [10, 11, 23, 24], [6, 7, 21], [6, 7, 22], [10,11,23], [10, 11, 24], [0, 1, 12, 13, 14, 15], [0, 1, 16, 17, 18, 19]]
  d_model: 256
  num_heads: 8
  num_layers_enc: 8
  num_layers_dec: 2
  d_ff: 1024
  max_seq_length: 8
  dropout: 0.
  t_m: 15
  body_avg: False
  #per_joints: True

work_dir: ./output_dir/ablation/enc_pe/pku_v2/

# pretraining
batch_size_pretrain: 128
epochs_pretrain: 400
warmup_epochs: 20
base_lr_pretrain: 0.001
eta_min_pretrain: 5e-4
weight_decay_pretrain: 0.05
mask_ratio: 0.8

weights_transformer_path: ./output_dir/ablation/enc_pe/pku_v2/final_weights/weights.pt # ./output_dir/ntu_xsub/final_weights/weights.pt

# lep
batch_size_lep: 64
epochs_lep: 100
base_lr_lep: 0.1
weight_decay_lep: 0.
num_classes: 60
